#!/usr/bin/env python3
"""Build the Phase 98 registered transfer-target unlock gate.

Phase 98 tries to turn the Phase 97 transfer-design blocker into concrete data
work. It can unlock a local baseline-first smoke target when a route has a
reproducible source manifest, a registration story, fixed splits, and baseline
comparators. It never opens A100 training.
"""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Any


UNLOCK_FIELDS = (
    "candidate_id",
    "source_route_id",
    "candidate_family",
    "dataset_id",
    "target_type",
    "source_manifest_status",
    "registration_status",
    "split_plan_status",
    "baseline_plan_status",
    "licensing_status",
    "paper_use",
    "phase99_local_smoke_allowed",
    "a100_training_allowed",
    "status",
    "priority",
    "next_action",
    "evidence",
)

PROTOCOL_FIELDS = (
    "protocol_id",
    "component",
    "requirement",
    "status",
    "artifact",
    "pass_condition",
    "stop_condition",
)


def _read_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        payload = json.load(handle)
    if not isinstance(payload, dict):
        raise ValueError(f"Expected object JSON at {path}")
    return payload


def _read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        rows = list(csv.DictReader(handle))
    if not rows:
        raise ValueError(f"Expected at least one row in {path}")
    return rows


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2, sort_keys=True)
        handle.write("\n")


def _write_csv(path: Path, rows: list[dict[str, Any]], fields: tuple[str, ...]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(fields), lineterminator="\n")
        writer.writeheader()
        for row in rows:
            writer.writerow({field: _csv_value(row.get(field)) for field in fields})


def _csv_value(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, float):
        return f"{value:.6f}"
    if isinstance(value, (dict, list)):
        return json.dumps(value, sort_keys=True)
    return str(value)


def _display_path(path: Path, root: Path | None = None) -> str:
    if root is not None:
        try:
            return path.resolve().relative_to(root.resolve()).as_posix()
        except ValueError:
            pass
    return path.as_posix()


def _default_paths(root: Path) -> dict[str, Path]:
    phase96 = root / "docs/results/phase96_pfhub_local_smoke_gate"
    phase97 = root / "docs/results/phase97_transfer_design_gate"
    return {
        "phase96_target_manifest": phase96 / "phase96_pfhub_style_target_manifest.json",
        "phase97_gate": phase97 / "phase97_transfer_design_gate.json",
        "phase97_transfer_routes": phase97 / "phase97_transfer_route_table.csv",
    }


def _truthy(value: str | bool | None) -> bool:
    if isinstance(value, bool):
        return value
    return str(value).strip().lower() in {"true", "1", "yes"}


def _phase97_fixed_signal_available(phase97_gate: dict[str, Any]) -> bool:
    mechanisms = phase97_gate.get("positive_mechanisms")
    return (
        bool(phase97_gate.get("positive_mechanisms"))
        and isinstance(mechanisms, list)
        and "fixed_green_function_features" in mechanisms
    )


def build_registered_surrogate_card(phase96_target: dict[str, Any]) -> dict[str, Any]:
    target_id = phase96_target.get("target_id", "phase96_pfhub_style_heat_source_v1")
    return {
        "candidate_id": "phase98_generated_pfhub_registered_surrogate_v1",
        "source_phase": 96,
        "source_target_id": target_id,
        "dataset_family": "generated_registered_surrogate",
        "registration_story": (
            "Source coordinates, target coordinates, source trajectory, diffusivity, and train/validation/test "
            "grids are generated by the same deterministic analytic specification; registration is exact by definition."
        ),
        "source_manifest": {
            "generator": "scripts/server/build_phase96_pfhub_local_smoke_gate.py",
            "target_manifest": "docs/results/phase96_pfhub_local_smoke_gate/phase96_pfhub_style_target_manifest.json",
            "alpha": phase96_target.get("alpha"),
            "source_x0": phase96_target.get("source_x0"),
            "source_velocity": phase96_target.get("source_velocity"),
            "source_sigma2": phase96_target.get("source_sigma2"),
        },
        "split_plan": {
            "train_grid": phase96_target.get("splits", {}).get("train_grid", {}),
            "validation_grid": phase96_target.get("splits", {}).get("validation_grid", {}),
            "test_grid": phase96_target.get("splits", {}).get("test_grid", {}),
            "selection_rule": "candidate and hyperparameter selection must use train/validation only",
        },
        "baseline_plan": [
            "low_order_interpolation",
            "vanilla_deterministic_surrogate",
            "fixed_green_function_features",
            "random_collocation_same_budget",
        ],
        "metric_contract": [
            "global_rmse",
            "pde_residual_rmse",
            "hot_q90_rmse",
            "gradient_q90_rmse",
            "coverage_if_bayesian",
        ],
        "not_a_claim": [
            "not AM-Bench evidence",
            "not a replacement for Phase 55/60/74 spot_size floor",
            "not permission for A100 training",
            "not evidence that pad or single-track source-path registration is solved",
        ],
    }


def _surrogate_unlock_row(card: dict[str, Any], fixed_signal_available: bool) -> dict[str, Any]:
    allowed = fixed_signal_available
    return {
        "candidate_id": card["candidate_id"],
        "source_route_id": "phase97_pfhub_only_appendix_extension",
        "candidate_family": "generated_registered_surrogate",
        "dataset_id": card["source_target_id"],
        "target_type": "PFHub-style manufactured heat-source benchmark",
        "source_manifest_status": "generated_manifest_ready",
        "registration_status": "registered_by_analytic_definition",
        "split_plan_status": "fixed_train_validation_test_grids",
        "baseline_plan_status": "phase96_baseline_contract_ready",
        "licensing_status": "repo_generated_reproducible_artifact",
        "paper_use": "local mechanism benchmark or appendix only; not AM-Bench transfer evidence",
        "phase99_local_smoke_allowed": allowed,
        "a100_training_allowed": False,
        "status": "phase99_local_smoke_ready_no_a100" if allowed else "blocked_no_phase97_signal",
        "priority": 1,
        "next_action": (
            "enter Phase 99 local baseline-first smoke on generated registered surrogate"
            if allowed
            else "repair Phase 96/97 fixed-kernel signal before surrogate smoke"
        ),
        "evidence": "Phase 96 deterministic target manifest and Phase 97 PFHub-only route.",
    }


def _unlock_row_from_phase97_route(row: dict[str, str]) -> dict[str, Any]:
    route_id = row["route_id"]
    status = row.get("status", "")
    is_open = _truthy(row.get("phase98_local_smoke_allowed"))
    if is_open:
        unlock_status = "phase99_local_smoke_ready_no_a100"
        next_action = "enter Phase 99 local baseline-first smoke for registered route"
    elif status == "blocked_missing_registration":
        unlock_status = "blocked_registration_evidence_required"
        next_action = "provide camera-to-galvo or equivalent coordinate registration before local smoke"
    elif status == "blocked_no_data_card":
        unlock_status = "blocked_source_manifest_data_card_required"
        next_action = "provide public source manifest, registration story, split plan, and baseline plan"
    elif status == "synthetic_appendix_only":
        unlock_status = "handled_by_generated_surrogate_candidate"
        next_action = "use generated registered surrogate row for local mechanism smoke"
    elif status.startswith("blocked"):
        unlock_status = status
        next_action = row.get("next_action") or "resolve transfer blocker before local smoke"
    else:
        unlock_status = "diagnostic_only"
        next_action = row.get("next_action") or "keep as diagnostic evidence"
    return {
        "candidate_id": f"phase98_unlock_{route_id}",
        "source_route_id": route_id,
        "candidate_family": row.get("route_family", ""),
        "dataset_id": row.get("dataset_id", ""),
        "target_type": row.get("transfer_target", ""),
        "source_manifest_status": "missing_or_inherited_from_blocked_route",
        "registration_status": row.get("registration_status", ""),
        "split_plan_status": row.get("split_status", ""),
        "baseline_plan_status": row.get("baseline_status", ""),
        "licensing_status": "inherited_or_missing",
        "paper_use": row.get("status", ""),
        "phase99_local_smoke_allowed": is_open,
        "a100_training_allowed": False,
        "status": unlock_status,
        "priority": int(row.get("priority") or 99) + 10,
        "next_action": next_action,
        "evidence": row.get("evidence", ""),
    }


def build_unlock_rows(
    *,
    phase97_gate: dict[str, Any],
    transfer_rows: list[dict[str, str]],
    surrogate_card: dict[str, Any],
) -> list[dict[str, Any]]:
    fixed_signal_available = _phase97_fixed_signal_available(phase97_gate)
    rows = [_surrogate_unlock_row(surrogate_card, fixed_signal_available)]
    rows.extend(_unlock_row_from_phase97_route(row) for row in transfer_rows)
    return sorted(rows, key=lambda row: int(row["priority"]))


def build_protocol_rows() -> list[dict[str, Any]]:
    return [
        {
            "protocol_id": "P98-PROT-001",
            "component": "source_manifest",
            "requirement": "Every unlocked target needs a reproducible source manifest or deterministic generator.",
            "status": "defined",
            "artifact": "phase98_registered_surrogate_data_card.json or external source manifest",
            "pass_condition": "source is public or generated from committed code and records parameters",
            "stop_condition": "source cannot be regenerated or inspected",
        },
        {
            "protocol_id": "P98-PROT-002",
            "component": "registration_story",
            "requirement": "Source and target coordinates must be registered without using test labels.",
            "status": "defined",
            "artifact": "candidate row registration_status",
            "pass_condition": "coordinate mapping is exact, documented, or verified before local smoke",
            "stop_condition": "only independent-rescale or test-selected alignment is available",
        },
        {
            "protocol_id": "P98-PROT-003",
            "component": "baseline_plan",
            "requirement": "Local smoke must compare to simple and route-relevant baselines before any training scale-up.",
            "status": "defined",
            "artifact": "candidate row baseline_plan_status",
            "pass_condition": "mean/low-order, deterministic surrogate, and feature baselines are specified",
            "stop_condition": "candidate cannot be compared to a simpler baseline",
        },
        {
            "protocol_id": "P98-PROT-004",
            "component": "compute_governance",
            "requirement": "Phase 98 may only unlock Phase 99 local smoke.",
            "status": "defined",
            "artifact": "phase98_registered_target_unlock_gate.json",
            "pass_condition": "A100 flags remain false",
            "stop_condition": "any route tries to open A100 before Phase 99 local smoke",
        },
    ]


def build_gate(
    *,
    phase97_gate: dict[str, Any],
    unlock_rows: list[dict[str, Any]],
) -> dict[str, Any]:
    ready_rows = [row for row in unlock_rows if row["phase99_local_smoke_allowed"]]
    ambench_ready = [
        row
        for row in ready_rows
        if row["dataset_id"] not in {"phase96_pfhub_style_heat_source_v1", "pfhub_style_local"}
    ]
    if not _phase97_fixed_signal_available(phase97_gate):
        status = "blocked_no_phase97_positive_mechanism"
        next_action = "close fixed-kernel transfer; no positive mechanism is available"
        phase99_allowed = False
    elif ready_rows:
        status = "registered_surrogate_unlocked_no_a100"
        next_action = "enter Phase 99 local baseline-first smoke on the generated registered surrogate"
        phase99_allowed = True
    else:
        status = "blocked_no_unlock_candidate"
        next_action = "resolve pad registration or provide an external registered data card"
        phase99_allowed = False
    return {
        "status": status,
        "source_phase97_status": phase97_gate.get("status"),
        "phase99_local_smoke_allowed": phase99_allowed,
        "a100_training_allowed_now": False,
        "a100_80gb_request_now": False,
        "submission_ready": False,
        "unlock_rows": len(unlock_rows),
        "phase99_candidate_rows": len(ready_rows),
        "ambench_phase99_candidate_rows": len(ambench_ready),
        "blocked_rows": sum(1 for row in unlock_rows if str(row["status"]).startswith("blocked")),
        "preferred_phase99_candidate": ready_rows[0]["candidate_id"] if ready_rows else "none",
        "am_bench_transfer_unlocked": bool(ambench_ready),
        "next_action": next_action,
        "required_before_a100_training": [
            "Phase 99 local baseline-first smoke",
            "non-worse global/hot/gradient metrics",
            "strong baseline comparison",
            "fixed split and no-test-leakage selection",
            "server validation from a pushed commit",
        ],
    }


def _markdown_table(rows: list[dict[str, Any]], columns: list[tuple[str, str]]) -> str:
    if not rows:
        return "_No rows._"
    header = "| " + " | ".join(label for _, label in columns) + " |"
    sep = "| " + " | ".join("---" for _ in columns) + " |"
    body = [
        "| " + " | ".join(_csv_value(row.get(key)).replace("\n", " ") for key, _ in columns) + " |"
        for row in rows
    ]
    return "\n".join([header, sep, *body])


def build_markdown(
    gate: dict[str, Any],
    unlock_rows: list[dict[str, Any]],
    protocol_rows: list[dict[str, Any]],
) -> str:
    return "\n".join(
        [
            "# Phase 98 Registered Transfer Target Unlock Gate",
            "",
            "## Gate Decision",
            "",
            f"Status: `{gate['status']}`.",
            f"Phase 99 local smoke allowed: `{str(gate['phase99_local_smoke_allowed']).lower()}`.",
            f"AM-Bench transfer unlocked: `{str(gate['am_bench_transfer_unlocked']).lower()}`.",
            f"A100 training allowed now: `{str(gate['a100_training_allowed_now']).lower()}`.",
            f"A100-SXM4-80GB request now: `{str(gate['a100_80gb_request_now']).lower()}`.",
            "",
            "Phase 98 can unlock local smoke for a registered target or generated surrogate only. It is not an A100 training gate.",
            "",
            "## Unlock Candidates",
            "",
            _markdown_table(
                unlock_rows,
                [
                    ("candidate_id", "Candidate"),
                    ("dataset_id", "Dataset"),
                    ("registration_status", "Registration"),
                    ("status", "Status"),
                    ("phase99_local_smoke_allowed", "Phase 99"),
                    ("next_action", "Next action"),
                ],
            ),
            "",
            "## Protocol",
            "",
            _markdown_table(
                protocol_rows,
                [
                    ("protocol_id", "Protocol"),
                    ("component", "Component"),
                    ("pass_condition", "Pass"),
                    ("stop_condition", "Stop"),
                ],
            ),
            "",
            "## Next Action",
            "",
            gate["next_action"],
            "",
        ]
    )


def build_package(
    root: Path,
    output_dir: Path,
    paths: dict[str, Path] | None = None,
) -> dict[str, Any]:
    resolved = _default_paths(root)
    if paths:
        resolved.update(paths)

    phase96_target = _read_json(resolved["phase96_target_manifest"])
    phase97_gate = _read_json(resolved["phase97_gate"])
    transfer_rows = _read_csv(resolved["phase97_transfer_routes"])

    surrogate_card = build_registered_surrogate_card(phase96_target)
    unlock_rows = build_unlock_rows(
        phase97_gate=phase97_gate,
        transfer_rows=transfer_rows,
        surrogate_card=surrogate_card,
    )
    protocol_rows = build_protocol_rows()
    gate = build_gate(phase97_gate=phase97_gate, unlock_rows=unlock_rows)

    output_dir.mkdir(parents=True, exist_ok=True)
    unlock_path = output_dir / "phase98_unlock_candidate_table.csv"
    protocol_path = output_dir / "phase98_unlock_protocol.csv"
    surrogate_card_path = output_dir / "phase98_registered_surrogate_data_card.json"
    gate_path = output_dir / "phase98_registered_target_unlock_gate.json"
    markdown_path = output_dir / "phase98_registered_target_unlock_gate.md"
    manifest_path = output_dir / "phase98_registered_target_unlock_gate_manifest.json"

    _write_csv(unlock_path, unlock_rows, UNLOCK_FIELDS)
    _write_csv(protocol_path, protocol_rows, PROTOCOL_FIELDS)
    _write_json(surrogate_card_path, surrogate_card)
    _write_json(gate_path, gate)
    markdown_path.write_text(build_markdown(gate, unlock_rows, protocol_rows), encoding="utf-8")

    manifest = {
        "phase": 98,
        "objective": "registered_transfer_target_unlock_gate",
        "inputs": {key: _display_path(path, root) for key, path in sorted(resolved.items())},
        "outputs": {
            "unlock_candidate_table": _display_path(unlock_path, root),
            "unlock_protocol": _display_path(protocol_path, root),
            "registered_surrogate_data_card": _display_path(surrogate_card_path, root),
            "gate_json": _display_path(gate_path, root),
            "markdown": _display_path(markdown_path, root),
            "manifest": _display_path(manifest_path, root),
        },
        "counts": {
            "unlock_rows": len(unlock_rows),
            "protocol_rows": len(protocol_rows),
            "phase99_candidate_rows": gate["phase99_candidate_rows"],
            "ambench_phase99_candidate_rows": gate["ambench_phase99_candidate_rows"],
            "blocked_rows": gate["blocked_rows"],
        },
        "gate": gate,
        "phase97_gate": {
            "status": phase97_gate.get("status"),
            "positive_mechanisms": phase97_gate.get("positive_mechanisms"),
            "phase98_local_smoke_allowed": phase97_gate.get("phase98_local_smoke_allowed"),
        },
        "source_target": {
            "target_id": phase96_target.get("target_id"),
            "target_type": phase96_target.get("target_type"),
        },
    }
    _write_json(manifest_path, manifest)
    return manifest


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path("."))
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("docs/results/phase98_registered_target_unlock_gate"),
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    root = args.root.resolve()
    output_dir = args.output_dir
    if not output_dir.is_absolute():
        output_dir = root / output_dir
    manifest = build_package(root=root, output_dir=output_dir)
    print(json.dumps(manifest, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
